### ISSUE TITLE
Links to detailed docs from "All torchmetrics" page are dead

### ISSUE THREAD

**Issue by AnkushMalaker** [Lightning-AI/metrics#1099]
## 📚 Documentation

For typos and doc fixes, please go ahead and:

1. Create an issue.
1. Fix the typo.
1. Submit a PR.

Thanks!

While navigating to details of any metrics from https://torchmetrics.readthedocs.io/en/stable/pages/all-metrics.html , I get a 404 error. 
For example, MAP has the following dead line : https://torchmetrics.readthedocs.io/en/stable/pages/detection/mean_average_precision.html
while selecting it from the sidebar gives me this working link:
https://torchmetrics.readthedocs.io/en/stable/detection/mean_average_precision.html

I'm not familiar with sphynx or ReadTheDocs so I would be able to submit a PR to fix the issue if someone could lead me where to look or edit those.
Thanks for the awesome work.

**Comment by SkafteNicki** [comment]
cc: @ethanwharris can you help what is going wrong here?

**Comment by stancld** [comment]
@SkafteNicki -- a potential hotfix might be to move `all-metrics.rst` from `./docs/source/pages/` to `./docs/source/` and update a path in `index.rst` accordingly.
I don't know what the real problem is, but currently, there's a problem that nesting `all-metrics.rst` into `pages` folder adds `pages` into the URL :/
