### ISSUE TITLE
Import binary/multiclass/multilabel classification metrics into __init__

### ISSUE THREAD

**Issue by ZhaofengWu** [Lightning-AI/metrics#1264]
## 🚀 Feature

For example, just like how users can do `from torchmetrics import Accuracy`, it'd ideal if users could do `from torchmetrics import MulticlassAccuracy` too.

**Comment by justusschock** [comment]
Hey, thanks for this issue.

We actually thought about this a lot! The behaviour `from torchmetrics import Accuracy` originated in the time where we didn't have too many metrics so it made sense to have them all on root level.

Over time (and especially after the recent classification refactor), the number of metrics grew to a level where it did not make sense to pursue this further. So we decided to group metrics w.r.t their task.

Importing them all to the root level would pollute the root level in a way, that features like IDE autocomplete would not be usable any more due to the sheer number of metrics available. 
A nice side-effect is that users actually need to think about what task they want to evaluate and thereby choose the correct metric.

Finally we think that for these reasons it is not too much to require minimally longer import statements.

We are also not sure, whether we actually want to keep metrics like `Accuracy` on the toplevel or want to remove the import there and make them only importable from the respective subpackage as well

**Comment by ZhaofengWu** [comment]
Yes, that definitely makes sense! My use case is that I want the client of my code to simply obtain a metric with a string. In other words I want the entire training process to be specifiable with strings in a config file or something. Previously I could do `getattr(torchmetrics, metric_name)`, but with the refactor this is no longer possible (at least if I want to be using the recommended new classes). What do you think my best option is to implement this? Can the root Metric class implement a `by_name` class method or something?

**Comment by SkafteNicki** [comment]
@ZhaofengWu you should be able to do what you are already doing with nested `getattr`:
![image](https://user-images.githubusercontent.com/24896311/195416013-074d3b1a-7dfd-45bd-a11c-83b06a422d84.png)

**Comment by ZhaofengWu** [comment]
Right, yes, that's a workaround. I guess ideally specifying `"MulticlassAccuracy"` is easier than `("classification", "MulticlassAccuracy")` in a config file, and technically `"classification"` is unnecessary because there's only one `MulticlassAccuracy` metric.

**Comment by SkafteNicki** [comment]
> Right, yes, that's a workaround. I guess ideally specifying `"MulticlassAccuracy"` is easier than `("classification", "MulticlassAccuracy")` in a config file, and technically `"classification"` is unnecessary because there's only one `MulticlassAccuracy` metric.

Yes, as long as you are only trying to pull metrics from one subpackage e.g. not also needing `regression` metrics for the same experiment (which seems weird to me) then this should definitely work

**Comment by ZhaofengWu** [comment]
I meant for cases when someone does need metrics from different subpackages. But not necessarily in the same experiment. For example, I want an experiment to be specifiable with something like
```
"model_name": xxx,
"dataset_name": xxx,
"metric_name": "MulticlassAccuracy",
```
And in my code I can find the corresponding metric from torchmetrics using only "metric_name" (previous, with `getattr(torchmetrics, metric_name)`). This is currently impossible unless I hardcode "classification", but that's also not ideal because people might need non-classification metrics (again, not necessarily in the same experiment as a classification metric, but something my code should support). I can ask the user to specify "classification", but that's technically redundant because "MulticlassAccuracy" by itself is sufficient for uniquely pointing to a metric. Not a huge nuisance, but if there's a simpler way to do it that'd be ideal.
