### ISSUE TITLE
Can not import total variation

### ISSUE THREAD

**Issue by zhangzp9970** [Lightning-AI/metrics#1355]
## 🐛 Bug

can not import total variation. It seems that the TotalVariation is not imported in the __init__.py

### To Reproduce

Steps to reproduce the behavior...
from torchmetrics import TotalVariation
from torchmetrics.functional import total_variation

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source):
- Python & PyTorch Version (e.g., 1.0):
- Any other relevant information such as OS (e.g., Linux):
torchmetrics              0.10.3             pyhd8ed1ab_0    conda-forge

**Comment by zhangzp9970** [comment]
The link of the source button on the website is also wrong

**Comment by SkafteNicki** [comment]
Hi @zhangzp9970,
Its because total variation have not been released yet, it can be found on master, so to get it before the next release you can install with:
```
pip install git+https://github.com/Lightning-AI/metrics.git
```
If you have found it in the documentation of torchmetrics it may be because you are looking at the `latest` version and not the `stable` version:
![image](https://user-images.githubusercontent.com/24896311/203487402-d9b02817-8624-4d39-8615-afd152a583e8.png)

**Comment by zhangzp9970** [comment]
Thank you for your reply!
