### ISSUE TITLE
f1_score yields different results for task binary and mulitlclass with two classes

### ISSUE THREAD

**Issue by Maxl94** [Lightning-AI/metrics#1396]
## 🐛 Bug

The `f1_score` return different results for `task='binary'` and `task='mulitlclass', num_classes=2` with them same tensors.

### To Reproduce

Just run the code sample below.

#### Code sample

```python
import torch
from torchmetrics.functional import f1_score
from sklearn.metrics import f1_score as f1_score_sk

a = torch.tensor([0,0,1,1])
b = torch.tensor([0,1,1,1])

f1_score(a, b, task='binary')
# Out[25]: tensor(0.8000)

f1_score(a, b, task='multiclass', num_classes=2)
# Out[26]: tensor(0.7500)

f1_score_sk(a, b)
# Out[34]: 0.8

```

### Expected behavior

The `f1_score` should be the same in this case.

### Environment

```sh
pytorch-lightning             1.8.5
torch                         1.13.1
torchmetrics                  0.11.0
```

```sh
ProductName:		macOS
ProductVersion:		13.0.1
BuildVersion:		22A400
```

**Comment by SkafteNicki** [comment]
Hi @Maxl94,
That is because the core definition is different for binary and multiclass. Essentially, there exist a fixed definition in the binary case (first equation):
https://en.wikipedia.org/wiki/F-score
however, what is never really mentioned is that this definition does not have a one to one matching definition for multiclass case. For multiclass you need a method of reducing over the multiple classes regardless of how many classes you have. The default choice of class reduction in torchmetrics is `micro` which globally adds the underlying statistics for all classes. Thus when you get a different result its basically because another formula is used, nothing wrong.

The way around is to pass `average=None` which will return the score per class where we can correctly identify that the score for class 1 is identical to the binary score (as per the standard definition):
```python
f1_score(a, b, task='multiclass', num_classes=2, average=None)
Out[10]: tensor([0.6667, 0.8000])
```
Hope this clears up the confusion. In general always use `task='binary'` if input is binary.
