### ISSUE TITLE
Thresholds not working?

### ISSUE THREAD

**Issue by entangledloops** [Lightning-AI/metrics#1443]
## 🐛 Bug

Using `torchmetrics.PrecisionRecallCurve` / `torchmetrics.ROC` produce an error when setting `thresholds` to something other than `None`.

### To Reproduce

```py
import torch
import torchmetrics
x = torch.zeros(5, 2)
y = torch.zeros(5, 2)
thresholds = torch.linspace(0, 1, 100)
prc = torchmetrics.PrecisionRecallCurve(task="multilabel", num_labels=2, thresholds=thresholds)
prc(x, y)
```

Output:
```
File .../torchmetrics/utilities/data.py:228, in _bincount(x, minlength)
    226         output[i] = (x == i).sum()
    227     return output
--> 228 return torch.bincount(x, minlength=minlength)

RuntimeError: "bincount_cpu" not implemented for 'Float'
```

#### Code sample

See above.

### Expected behavior

Works as documented, where a `List` or `Tensor` of thresholds can be manually provided, rather than using the autobin feature.

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source): conda, 0.11
- Python & PyTorch Version (e.g., 1.0): Python 3.10, PyTorch 1.13.1
- Any other relevant information such as OS (e.g., Linux): LUbuntu 22.04

### Additional context

N/A

**Comment by SkafteNicki** [comment]
Hi @entangledloops,
Thanks for reporting this. The problem seems to be that `PrecisionRecallCurve` always expect the `target` tensor to have dtype `int` (or `long`) but in your example you are providing an `float` tensor. See docs here for that info:
https://torchmetrics.readthedocs.io/en/stable/classification/precision_recall_curve.html#multilabelprecisionrecallcurve
Thus changing `y = torch.zeros(5, 2)` to `y = torch.zeros(5, 2, dtype=torch.int)` works. In PR #1457 a explicit dtype check will be added.
