### ISSUE TITLE
Make MetricsCollection work with dict of other MetricsCollection

### ISSUE THREAD

**Issue by rusmux** [Lightning-AI/metrics#1459]
## 🚀 Feature

It would be nice if `MetricsCollection` worked with dict of other `MetricsCollection`. For example:

```Python
metrics = MetricsCollection([Accuracy(), F1Score()])

self.metrics = MetricsCollection({
    "train": metrics.clone(prefix="train_"),
    "val": metrics.clone(prefix="val_"),
    "test": metrics.clone(prefix="test_"),
})
```

### Motivation

Currently, `MetricsCollection` doesn't work if you pass a dict of other `MetricCollection`. The workaround is to use just `dict`, but this way metrics are not automatically transferred to the specified trainer device. Another workaround is to use `torch.nn.ModuleDict` but you can encounter errors like that "train" dict key is already in use.

### Pitch

`MetricsCollection` work with dict of other `MetricsCollection`.

**Comment by justusschock** [comment]
Hi, this is actually done on purpose. MetricsCollections are to share states and thereby speedup computations. This is something that should not be done across different data splits.

I'd recommend to do something like this:
```python
self.metrics_train = metric.clone()
self.metrics_val = metrics.clone()
self.metrics_test = metrics.clone()
```

 and then in the steps instead of `self.metrics['train']` do `getattr(self, 'metrics_train')`

**Comment by rusmux** [comment]
Oh, I see, thank you!
