### ISSUE TITLE
MPS not supported with Accuracy

### ISSUE THREAD

**Issue by aniketmaurya** [Lightning-AI/metrics#1611]
## 🐛 Bug

While training with the MPS accelerator I got the error to set `PYTORCH_ENABLE_MPS_FALLBACK=1`.

```
NotImplementedError: The operator 'aten::_unique2' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
```

### To Reproduce

Steps to reproduce the behavior...

<details>
  <summary>Code sample</summary>

</details>

### Environment

- TorchMetrics version (and how you installed TM, e.g. `conda`, `pip`, build from source):
- Python & PyTorch Version (e.g., 1.0):
- Any other relevant information such as OS (e.g., Linux):

**Comment by justusschock** [comment]
Hey @aniketmaurya, this is kind of known and an issue with MPS on the pytorch side since they just don't support too many ops yet. However, we unfortunately cannot replace most of the operations as they are core to the computation here.

The same happens btw. if you try to train certain models. Just set the flag as given by the error message and you should be good. It will run only this specific op (`torch.unique`) on CPU and everything else on MPS. Due to the shared memory architecture of apple silicon chips, there should be no overhead from memory transfer between CPU and gpu.

**Comment by SkafteNicki** [comment]
Agree with @justusschock on this :)
However, I think that for accuracy you can actually go around using the `torch.unique` operator by setting `validate_args=False` when initializing the metric:
```python
import torch
from torchmetrics import Accuracy
preds = torch.rand(20,)
target = torch.randint(2, (20,))
metric = Accuracy(task="binary", validate_args=False)
acc = metric(preds, target)
```
this disable input validation but if you know that your input is of the correct shape that should not be a problem. @justusschock can you check if the example runs without problems (I do not have an MPS device)?

**Comment by SkafteNicki** [comment]
In addition, this can be solved by installing Pytorch nightly (see this issue https://github.com/pytorch/pytorch/issues/92821) as MPS support for `torch.unique` has been added in this PR: https://github.com/pytorch/pytorch/pull/88532.
