### ISSUE TITLE
[Metrics] Panoptic Quality

### ISSUE THREAD

**Issue by justusschock** [Lightning-AI/metrics#50]
## 🚀 Feature
Implement Panoptic Quality

**Comment by InCogNiTo124** [comment]
A polite request for reopening the issue, PQ is an important metric and it would be great to have it

**Comment by niberger** [comment]
Hello, I will give a try this week, inspired from the COCO implementation: https://github.com/cocodataset/panopticapi/blob/master/panopticapi/evaluation.py

Any preliminary comments are most welcome, especially on the signature that the methods should have.
In any case I will submit a draft PR soon.

**Comment by niberger** [comment]
Regarding the spirit of implementation to adopt I do have a few question since it is my first contribution to PL.
- Should the metric return a single float (the actual panoptic quality) or should it return a dict of detailed intermediate results like in the reference implementation in COCO api?
- If I see small bugs/differences between the reference implementation and the reference paper, which one should I follow?

[Reference paper](https://arxiv.org/abs/1801.00868)
[Reference implementation](https://github.com/cocodataset/panopticapi/blob/master/panopticapi/evaluation.py)
[My work so far](https://github.com/niberger/metrics/blob/feature/50_panoptic_quality/torchmetrics/detection/panoptic_quality.py)

**Comment by bhack** [comment]
For Boundary PQ (Panoptic Quality) see https://github.com/Lightning-AI/metrics/issues/1500#issuecomment-1427732520
https://bowenc0221.github.io/boundary-iou/

**Comment by justusschock** [comment]
Reopening for missing things

- better test coverage
- batched support

**Comment by marcocaccin** [comment]
Ready to close this issue now? 😉

**Comment by tommiekerssies** [comment]
So this does not include the matching of the predicted and ground truth thing segments?

**Comment by aymuos15** [comment]
https://github.com/BrainLesion/panoptica
