### ISSUE TITLE
Accuracy metric - negative `ignore_index` fails when combined with `subset_accuracy=True`

### ISSUE THREAD

**Issue by antifriz** [Lightning-AI/metrics#961]
### To Reproduce

Combine `ignore_index=-1` with `subset_accuracy=True`

#### Code sample
```python
import torch
import torchmetrics

accuracy = torchmetrics.Accuracy(
    subset_accuracy=True,
    ignore_index=-1,
)
# element with index 2 will always be outputted
preds = torch.arange(45, dtype=torch.float).reshape(3, 5, 3).permute(0, 2, 1)
target = torch.tensor(
    [
        [2, 2, 2, 0, -1],
        [2, 2, -1, -1, -1],
        [2, 2, 2, 2, 2],
    ],
    dtype=torch.int64,
)
accuracy.update(preds=preds, target=target)
```

### Expected behavior

Not crashing

### Environment

- OS (e.g., Linux): OSX
- Python & PyTorch Version (e.g., 1.0): 3.9 (torch==1.11.0, torchmetrics==0.8.0)
- How you installed PyTorch (`conda`, `pip`, build command if you used source): `pip`
- Any other relevant information:

### Additional context
Stack trace
```bash

Traceback (most recent call last):
  File "main.py", line 18, in <module>
    accuracy.update(preds=preds, target=target)
  File ".../python3.9/site-packages/torchmetrics/metric.py", line 312, in wrapped_func
    update(*args, **kwargs)
  File ".../python3.9/site-packages/torchmetrics/classification/accuracy.py", line 233, in update
    correct, total = _subset_accuracy_update(
  File ".../python3.9/site-packages/torchmetrics/functional/classification/accuracy.py", line 224, in _subset_accuracy_update
    preds, target, mode = _input_format_classification(
  File ".../python3.9/site-packages/torchmetrics/utilities/checks.py", line 432, in _input_format_classification
    target = to_onehot(target, max(2, num_classes))  # type: ignore
  File ".../python3.9/site-packages/torchmetrics/utilities/data.py", line 99, in to_onehot
    return tensor_onehot.scatter_(1, index, 1.0)
RuntimeError: index -1 is out of bounds for dimension 1 with size 3
```

**Comment by SkafteNicki** [comment]
Issue will be fixed by classification refactor: see this issue https://github.com/Lightning-AI/metrics/issues/1001 and this PR https://github.com/Lightning-AI/metrics/pull/1195 for all changes

Small recap: This issue describes that using an negative `ignore_index` fails when combined with `subset_accuracy=True`. After the refactor, `accuracy` will no longer support the `subset_accuracy` argument. Instead this functionality have been split into its own metric called `exact_match`. This metric (together with all other classification metrics) now support negative `ignore_index` arguments.
```python
from torchmetrics.functional import multilabel_exact_match
import torch
preds = torch.tensor([[0.11, 0.22, 0.84], [0.73, 0.33, 0.92]])
target = torch.tensor([[0, 1, -1], [1, 0, 1]])
multilabel_exact_match(preds, target, num_labels=3, ignore_index=-1)
```
which works and gives the correct result.
Issue will be closed when https://github.com/Lightning-AI/metrics/pull/1195 is merged.
